# Generated by Django 6.1.1 on 2026-09-30 12:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nomi')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Ikonka')),
            ],
            options={
                'verbose_name': 'Jihoz',
                'verbose_name_plural': 'Jihozlar',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
            ],
            options={
                'verbose_name': 'Sevimli',
                'verbose_name_plural': 'Sevimlilar',
            },
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('description', models.TextField(max_length=5000, verbose_name='Tavsif')),
                ('type', models.CharField(choices=[('whole_apartment', 'Butun kvartira'), ('room', 'Xona'), ('bedspace', 'Joy')], max_length=20, verbose_name='Turi')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Narx')),
                ('currency', models.CharField(choices=[('UZS', "So'm"), ('USD', 'Dollar')], default='UZS', max_length=3, verbose_name='Valyuta')),
                ('deposit', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Depozit')),
                ('city', models.CharField(db_index=True, max_length=100, verbose_name='Shahar')),
                ('district', models.CharField(blank=True, max_length=100, verbose_name='Tuman')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='Manzil')),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Kenglik')),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Uzunlik')),
                ('rooms', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Xonalar soni')),
                ('area', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Maydoni (m²)')),
                ('floor', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Qavat')),
                ('total_floors', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Binoning qavatlari')),
                ('current_residents', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Hozirgi yashovchilar')),
                ('residents_gender', models.CharField(choices=[('male', 'Erkak'), ('female', 'Ayol'), ('unknown', "Ko'rsatilmagan")], default='unknown', max_length=10, verbose_name='Yashovchilar jinsi')),
                ('smoking_allowed', models.BooleanField(default=False, verbose_name='Chekishga ruxsat')),
                ('pets_allowed', models.BooleanField(default=False, verbose_name='Uy hayvonlariga ruxsat')),
                ('available_from', models.DateField(blank=True, null=True, verbose_name="Bo'sh bo'lish sanasi")),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('active', 'Faol'), ('archived', 'Arxivlangan'), ('moderation', 'Moderatsiyada'), ('rejected', 'Rad etilgan')], db_index=True, default='active', max_length=20, verbose_name='Status')),
            ],
            options={
                'verbose_name': "E'lon",
                'verbose_name_plural': "E'lonlar",
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('image', models.ImageField(upload_to='listings/', verbose_name='Rasm')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Tartib')),
            ],
            options={
                'verbose_name': "E'lon rasmi",
                'verbose_name_plural': "E'lon rasmlari",
                'ordering': ('order', 'created_at'),
            },
        ),
    ]
