# Generated by Django 6.1.1 on 2026-09-30 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('score', models.PositiveSmallIntegerField(default=0, verbose_name='Moslik foizi')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('accepted', 'Qabul qilindi'), ('rejected', 'Rad etildi')], default='pending', max_length=20, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Moslik',
                'verbose_name_plural': 'Mosliklar',
                'ordering': ('-score', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='RoommateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('looking_for', models.CharField(choices=[('have_place', 'Menda kvartira bor, sherik kerak'), ('looking', 'Kvartira ham, sherik ham qidiryapman')], default='looking', max_length=20, verbose_name="Yo'nalish")),
                ('budget_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Byudjet (min)')),
                ('budget_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Byudjet (max)')),
                ('city', models.CharField(db_index=True, max_length=100, verbose_name='Shahar')),
                ('district', models.CharField(blank=True, max_length=100, verbose_name='Tuman')),
                ('move_in_date', models.DateField(blank=True, null=True, verbose_name='Kirish sanasi')),
                ('gender_pref', models.CharField(choices=[('male', 'Erkak'), ('female', 'Ayol'), ('unknown', "Ko'rsatilmagan")], default='unknown', max_length=10, verbose_name='Jins afzalligi')),
                ('sleep_schedule', models.CharField(choices=[('early', 'Erta uxlayman'), ('late', 'Kech uxlayman'), ('flexible', 'Turlicha')], default='flexible', max_length=20, verbose_name='Uyqu tartibi')),
                ('cleanliness', models.CharField(choices=[('very_tidy', 'Juda toza'), ('tidy', 'Toza'), ('average', "O'rtacha"), ('relaxed', 'Etibormayman')], default='average', max_length=20, verbose_name='Tozalik darajasi')),
                ('smoking', models.BooleanField(default=False, verbose_name='Chekish')),
                ('guests_ok', models.BooleanField(default=True, verbose_name='Mehmon chaqirish')),
                ('pets', models.BooleanField(default=False, verbose_name='Uy hayvoni')),
                ('about', models.TextField(blank=True, max_length=2000, verbose_name="O'zim haqimda")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol anketa')),
            ],
            options={
                'verbose_name': 'Roommate anketa',
                'verbose_name_plural': 'Roommate anketalari',
                'ordering': ('-created_at',),
            },
        ),
    ]
