# Generated by Django 6.1.1 on 2026-10-01 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roommates', '0003_match_pair_normalization'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='match',
            new_name='roommates_m_user_a__c503ca_idx',
            old_name='roommates_m_user_a_7a1b2c_idx',
        ),
        migrations.RenameIndex(
            model_name='match',
            new_name='roommates_m_user_b__bed349_idx',
            old_name='roommates_m_user_b_3d4e5f_idx',
        ),
    ]
