# Generated by Django 6.1.1 on 2026-09-30 12:15

import apps.users.models.user
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Telefon raqam')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('role', models.CharField(choices=[('student', 'Talaba'), ('landlord', 'Kvartira egasi'), ('parent', 'Ota-ona'), ('moderator', 'Moderator'), ('admin', 'Admin')], db_index=True, default='student', max_length=20, verbose_name='Rol')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Verifikatsiya qilingan')),
                ('gender', models.CharField(choices=[('male', 'Erkak'), ('female', 'Ayol'), ('unknown', "Ko'rsatilmagan")], default='unknown', max_length=10, verbose_name='Jins')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi',
                'verbose_name_plural': 'Foydalanuvchilar',
            },
            managers=[
                ('objects', apps.users.models.user.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('full_name', models.CharField(blank=True, max_length=150, verbose_name="To'liq ism")),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Avatar')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name="Tug'ilgan sana")),
                ('gender', models.CharField(choices=[('male', 'Erkak'), ('female', 'Ayol'), ('unknown', "Ko'rsatilmagan")], default='unknown', max_length=10, verbose_name='Jins')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Shahar')),
                ('university', models.CharField(blank=True, max_length=200, verbose_name='Universitet')),
                ('faculty', models.CharField(blank=True, max_length=200, verbose_name='Fakultet')),
                ('course', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Kurs')),
                ('bio', models.TextField(blank=True, max_length=1000, verbose_name='Bio')),
                ('languages', models.CharField(blank=True, max_length=200, verbose_name='Tillar')),
                ('interests', models.CharField(blank=True, max_length=300, verbose_name='Qiziqishlar')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Profil',
                'verbose_name_plural': 'Profillar',
            },
        ),
        migrations.CreateModel(
            name='VerificationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('method', models.CharField(choices=[('university_email', 'Universitet email'), ('document', 'Talabalik hujjati + selfi'), ('applicant', 'Abituriyent hujjati')], max_length=30, verbose_name='Usul')),
                ('document_image', models.ImageField(blank=True, null=True, upload_to='verification/documents/', verbose_name='Hujjat rasmi')),
                ('selfie', models.ImageField(blank=True, null=True, upload_to='verification/selfies/', verbose_name='Selfi')),
                ('university_email', models.EmailField(blank=True, max_length=254, verbose_name='Universitet emaili')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('approved', 'Tasdiqlangan'), ('rejected', 'Rad etilgan')], db_index=True, default='pending', max_length=20, verbose_name='Status')),
                ('reject_reason', models.CharField(blank=True, max_length=300, verbose_name='Rad etish sababi')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_verifications', to=settings.AUTH_USER_MODEL, verbose_name="Ko'rib chiqqan")),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_requests', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': "Verifikatsiya so'rovi",
                'verbose_name_plural': "Verifikatsiya so'rovlari",
                'ordering': ('-created_at',),
            },
        ),
    ]
