# Generated by Django 6.1.1 on 2026-10-01 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, unique=True, verbose_name='Telegram ID'),
        ),
        migrations.AddField(
            model_name='profile',
            name='telegram_linked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Telegram bog'landi"),
        ),
        migrations.AddField(
            model_name='profile',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=64, verbose_name='Telegram username'),
        ),
    ]
