# Generated by Django 6.1.1 on 2026-10-01 20:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_telegram_id_profile_telegram_linked_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramLinkCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('code', models.CharField(db_index=True, max_length=16, unique=True, verbose_name='Kod')),
                ('expires_at', models.DateTimeField(verbose_name='Muddati')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='Urinishlar')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Ishlatilgan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_link_codes', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': "Telegram bog'lanish kodi",
                'verbose_name_plural': "Telegram bog'lanish kodlari",
                'ordering': ['-created_at'],
            },
        ),
    ]
