# Generated by Django 6.1.1 on 2026-09-30 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
            ],
            options={
                'verbose_name': 'Blok',
                'verbose_name_plural': 'Bloklar',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('target_type', models.CharField(choices=[('user', 'Foydalanuvchi'), ('listing', "E'lon"), ('message', 'Xabar')], db_index=True, max_length=20, verbose_name='Nishon turi')),
                ('target_id', models.PositiveIntegerField(db_index=True, verbose_name='Nishon id')),
                ('reason', models.CharField(choices=[('fake', "Soxta e'lon"), ('broker', 'Makler'), ('fraud', 'Firibgarlik'), ('abuse', 'Shikoyat / kuzatuvchilik'), ('spam', 'Spam'), ('minor_safety', 'Voyaga yetmagan xavfsizligi'), ('other', 'Boshqa')], max_length=30, verbose_name='Sabab')),
                ('description', models.TextField(blank=True, max_length=2000, verbose_name='Tavsif')),
                ('status', models.CharField(choices=[('open', 'Ochiq'), ('resolved', 'Hal qilindi'), ('dismissed', 'Bekor qilindi')], db_index=True, default='open', max_length=20, verbose_name='Status')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name="Ko'rib chiqilgan")),
            ],
            options={
                'verbose_name': 'Shikoyat',
                'verbose_name_plural': 'Shikoyatlar',
                'ordering': ('-created_at',),
            },
        ),
    ]
