# Generated by Django 6.1.1 on 2026-10-01 08:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='block',
            options={'ordering': ('-created_at',), 'verbose_name': 'Blok', 'verbose_name_plural': 'Bloklar'},
        ),
        migrations.AddIndex(
            model_name='block',
            index=models.Index(fields=['blocker', '-created_at'], name='reports_blo_blocker_c9633d_idx'),
        ),
    ]
