# Generated by Django 6.1.1 on 2026-09-30 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('type', models.CharField(choices=[('new_message', 'Yangi xabar'), ('verification_result', 'Verifikatsiya natijasi'), ('listing_interest', "E'longa qiziqish"), ('new_match', 'Yangi mos roommate')], db_index=True, max_length=30, verbose_name='Turi')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name="Ma'lumot")),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name="O'qilgan")),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name="O'qilgan vaqti")),
            ],
            options={
                'verbose_name': 'Bildirishnoma',
                'verbose_name_plural': 'Bildirishnomalar',
                'ordering': ('-created_at',),
            },
        ),
    ]
