# Generated by Django 6.1.1 on 2026-09-30 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
            ],
            options={
                'verbose_name': 'Suhbat',
                'verbose_name_plural': 'Suhbatlar',
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('text', models.TextField(blank=True, max_length=4000, verbose_name='Matn')),
                ('image', models.ImageField(blank=True, null=True, upload_to='chat/', verbose_name='Rasm')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name="O'qilgan vaqti")),
            ],
            options={
                'verbose_name': 'Xabar',
                'verbose_name_plural': 'Xabarlar',
                'ordering': ('created_at',),
            },
        ),
    ]
