# Generated by Django 6.1.1 on 2026-10-01 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_conversation_unique_pair'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='conversation',
            new_name='chat_conver_user_lo_863451_idx',
            old_name='chat_conve_user_low_a1b2c3_idx',
        ),
        migrations.RenameIndex(
            model_name='conversation',
            new_name='chat_conver_user_hi_d6312e_idx',
            old_name='chat_conve_user_high_d4e5f6_idx',
        ),
    ]
